Update template STAGETEST1

diff --git a/.harness/STAGETEST1_V1.yaml b/.harness/STAGETEST1_V1.yaml
--- a/.harness/STAGETEST1_V1.yaml
+++ b/.harness/STAGETEST1_V1.yaml
@@ -56,7 +56,79 @@ template:
                       - AllErrors
                     action:
                       type: Abort
-        rollbackSteps: []
+        rollbackSteps:
+          - stepGroup:
+              name: rollback-deploy
+              identifier: rollbackdeploy
+              steps:
+                - step:
+                    type: Run
+                    name: rollback-deploy
+                    identifier: rollbackdeploy
+                    spec:
+                      connectorRef: account.pypldockerhub
+                      image: alpine
+                      shell: Sh
+                      command: |-
+                        #!/bin/sh
+
+                        set -euo pipefail
+
+                        # Install dependencies
+                        apk add --no-cache jq curl
+
+                        # Validate input variables
+                        JOB_ID="${JOB_ID?Error: JOB_ID variable is not set.}"
+                        HRZ_TOKEN="${HRZ_TOKEN?Error: HRZ_TOKEN variable is not set.}"
+
+                        curl_output=$(curl -s "https://engineering.paypalcorp.com/genesis/api/genesis/api/v2/tenant/paypal/job/$JOB_ID/cancel" \
+                          -H "Token: $HRZ_TOKEN" \
+                          -H 'Provider: pingid' \
+                          --data-raw 'null')
+
+                        # Validate curl output
+                        if [ -z "$curl_output" ]; then
+                          echo "Error: curl returned empty JSON output"
+                          exit 1
+                        fi
+
+                        # Validate JSON
+                        if ! echo "$curl_output" | jq -e . > /dev/null 2>&1; then
+                          echo "Error: Invalid JSON response from curl. API response was: $curl_output"
+                          exit 1
+                        fi
+
+                        # Check for API error code
+                        if echo "$curl_output" | jq -e 'has("code")' > /dev/null 2>&1; then
+                          curl_code=$(echo "$curl_output" | jq -r '.code')
+                          echo "The 'code' field exists. Its value is: $curl_code"
+                          if [[ -n "$curl_code" ]] && [[ "$curl_code" -lt 200 || "$curl_code" -ge 300 ]]; then
+                            curl_message=$(echo "$curl_output" | jq -r '.message')
+                            echo "Error: HTTP $curl_code: $curl_message. Full response was: $curl_output"
+                            exit 1
+                          fi
+                        fi
+
+                        # Extract job ID only if the 'id' field exists and no curl error code was found.
+                        if echo "$curl_output" | jq -e 'has("id")' > /dev/null 2>&1; then
+                            CANCEL_JOB_ID=$(echo "$curl_output" | jq -r '.id')
+                        fi
+
+                        # Validate job ID
+                        if [ -z "$CANCEL_JOB_ID" ]; then
+                          echo "Error: Invalid JSON response. API response was: $curl_output"
+                          exit 1
+                        fi
+
+                        echo "Job ID: $CANCEL_JOB_ID"
+                        export CANCEL_JOB_ID
+                      envVariables:
+                        HRZ_TOKEN: <+stage.spec.execution.steps.deployjob.steps.getssohrztoken.output.outputVariables.SSO_HRZ_TOKEN>
+                        JOB_ID: <+execution.steps.deployjob.steps.polljob.spec.envVariables.JOB_ID>
+                      outputVariables:
+                        - name: CANCEL_JOB_ID
+                          type: String
+                          value: CANCEL_JOB_ID
     failureStrategies:
       - onFailure:
           errors:
